### PR TITLE
Non volatile storage

### PR DESCRIPTION
**Pull request by perigoso**
WIP 

- [x] partition table
- [x] partitions
- [x] flash/memory hal
- [ ] ~nvs "filesystem" (include wear leveling) (linked list?)~

here partitions and filesystem are not really those, in the traditional sense, its a very basic implementation of something akin to those

### CODE REVIEW

**Comment by perigoso** [comment]
I was going to write my own pseudo filesystem, but the longer i thought about it the bigger project it became, right now I'm inclined to write a memory block hal, and connect it to a new external component filesystem, looking at [littlefs](https://github.com/littlefs-project/littlefs) right now, i think it fits the application, the only thing bothering me is that every file uses at least 1 block of memory, which is one of the things i was trying to avoid, but we will have very little files so perhaps its not too bad, our edge case here is using the internal eeprom on the atmega32u4 which is only 1KB, but the block size is 4B/1W so it might just be manageable.

What do you think @FFY00 ?

**Comment by perigoso** [comment]
The 1KB limitation is complicated, but we don't strictly need to use a fs there, its definitely the better choice for targets where we have more space like the sammy

**Comment by FFY00** [comment]
Can you outline the benefits of using a (pseudo-)FS here? And which features would benefit from it, and how?
My quick impression is that we can do without it, but maybe I am misjudging the complexity of the implementation without a FS.

**Comment by perigoso** [comment]
The problem:
We want to store data structures, be it for configuration like profiles dpi and keyboard mappings, or statistics like boot count click count etc. and these need to be store in non volatile form.

The biggest problem we face is, where do we determine what to store where, and this sure sounds easy, we can just store them in a fixed location, but this makes for a very static configuration, fixed number and type of configurations, if we made changes like adding a configuration we would likely have to wipe the configuration etc, but the bigger problem with this is the wear on the memory, If we have some sort of data that gets update regularly, think active profile, we will be quickly wearing out that particular location, leading to the premature death of the device.
We need to spread the writes throughout the whole memory to make sure it wears evenly; Here comes dynamic location, this is much harder to solve, where do we save things, and worse, how do we know where we saved them! this is what I was naively trying to solve in my head, do we just write it to the next block? but then we need to erase the old when, and if the power goes out, which is the correct block, we could have a journal with the location of the data-structures, but that too needs to be stored, etc etc, when we try to solve all of these little problems what we are doing is writing a filesystem, so we might as well use something that has already solved those problems.

A bit ranty, and not very thorough in highlighting all of the problems, but I'm not good at this. I think this minimally highlights the problem.

What does a FS (littlefs in particular) solve?

- handles the where to store and find any particular "datastructure"
- deals with the wear leveling
- has power-loss resilience
- very dynamic

The problems it eventually brings:

- Even for a relatively simple FS, it's very complex
- memory, relatively small, but still 14K of rom!

Maybe there are simple and elegant ways of dealing with this in a more static maner.

The one approach I though of is, have a static data structure with all of the configurations we want to store, fixed size and locations, and have X blocks allocated for storage, and every time we write to it we store it in the next block, with a timestamp and maybe a crc for error checking and power loss resilience, we cycle through all of the blocks, like a circular buffer.

The problem with this is, very static
This is probably a good approach for the atmega using the internal eeprom.
We are using more and more powerfull devices, lets make use of them.

The beauty of our project is that this is totally optional on a target basis, the base for all this is the memory block hal that is usefull for all approaches

**Comment by perigoso** [comment]
either way, for now I'm going to implement a memory block hal, and we stay at that, it is enough to progress in other areas of the project like the protocol

**Comment by perigoso** [comment]
actually the more i think about it, this simplistic approach i mentioned at the end might just work well for everything, have a linked list with the various configs, and we just pack it and write it to the next logical block(s), we would use offsets instead of pointers, and we would need some sort of identification of the data

**Comment by FFY00** [comment]
Thank you for noting this down. I can see how a FS-ish approach might be beneficial, but I am a bit skeptical of the wear leveling 
mechanism, as it always needs to have a static table for the entrypoint. I haven't done a lot of research about this, but that is something that might be worth doing in the long run. Other concern is low memory targets, where the overhead of a FS might be unwanted.

I think we could actually have both approaches, as different targets might have different needs. The idea would be to define the non volatile HAL and then provide two (or more) implementations that targets could use, in this case, static memory and a FS-based one.
That should also fit pretty well in the timeline, as we can start things up right now with a static memory implementation, and then add a better, more complex, FS-based implementation in the future and have the targets that make sense switch to it. The main thing to keep in mind right now is the HAL design, we should make sure that it does not leak implementation details, as that will create more work for us in the future. How does this sound?

**Comment by perigoso** [comment]
Sounds good, I will try to implement and test a hal with a firts port for the internal flash of the sammy, I'm going to base myself on what these embbeded oriented FSs usually use for abstraction, this should lead to something future proof.

**Comment by mriise** [comment]
I was curious so i did some looking around and found this https://github.com/tock/tock/blob/master/libraries/tickv/SPEC.md, could be interesting instead of doing file based storage.

**Comment by perigoso** [comment]
Nice find, that key/value strategy is the same used by espressif in their idf, it's something i initially considered but then dismissed, the main disadvantages were the wasted space (1 key/value per block minimum), and the search algorith that would be needed (looking for the most recent key/values) and looking for available blocks, these are expensive.

With my idea both of those would be avoided, but it has its own disadvantages like the fact that you would need to rewrite the whole list, and you could only at best use half of the available space.

That said, theres something to be said about this flexible yet simple/elegant approach, I think it makes sense here.

The esp idf implementation is written in cpp so this is more useful to me.

**Comment by perigoso** [comment]
filesystems that served as inspiration/compatibility guideline for the hal
- [spiffs](https://github.com/pellepl/spiffs)
- [littlefs](https://github.com/littlefs-project/littlefs/blob/master/SPEC.md)
- [petit fatfs](http://elm-chan.org/fsw/ff/00index_p.html)
- [tickv](https://github.com/tock/tock/blob/master/libraries/tickv/SPEC.md)
- [mbed block dev](https://github.com/ARMmbed/mbed-os-example-blockdevice)

**Comment by perigoso** [comment]
Finally got to finish this, we still need some sort of higher level layer to manage key-value paris/files, but the fundamentals are implemented, Improvements can be made but we''l leave that to when they are actually needed

**Comment by perigoso** [comment]
the CI test seem to be broken, I believe it's due to a change github made not too long ago, to do with http?

**Pull request merged**
